### ISSUE TITLE
Define configuration YML

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/code-community#45]
Want to figure out a good config YML that can:

1. Allow configuring what files to update based on conditions
2. Allow configuring what contributions based on conditions

``` YAML
api:
  contributions:
    test:
      - condition
      - condition
  files:
    - '/api/README.md'
frontend:
  contributions:
    enhancement:
      - condition
      - condition
  files:
    - '/frontend/README.md'
```
